# Generated by Django 6.0.1 on 2026-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipfs_cid', models.CharField(help_text='CID returned by IPFS', max_length=255, unique=True)),
                ('blockchain_tx', models.CharField(help_text='Transaction hash where CID was stored', max_length=255)),
                ('blockchain_account', models.CharField(help_text='Blockchain account that stored the CID', max_length=255)),
                ('storage_time_taken', models.FloatField(help_text='Time taken to store data on blockchain (in seconds)')),
                ('transaction_per_second', models.FloatField(help_text='Transactions per second achieved during storage')),
                ('access_time_taken', models.FloatField(blank=True, help_text='Time taken to access/verify data from blockchain (in seconds)', null=True)),
                ('hash_matched', models.BooleanField(help_text='Whether the hash matched during verification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
